// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class AccountMapping
{
    public int Id { get; set; }

    public string TransactionType { get; set; }

    public int ChildAccountId { get; set; }

    public virtual ChildAccount ChildAccount { get; set; }
}