// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class AccountType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual AccountTypeMovement AccountTypeMovement { get; set; }

    public virtual ICollection<ParentAccount> ParentAccounts { get; set; } = new List<ParentAccount>();
}