// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class AccountTypeMovement
{
    public int AccountTypeId { get; set; }

    public string IncreaseBy { get; set; }

    public virtual AccountType AccountType { get; set; }
}