// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Adjustment
{
    public int AdjustmentId { get; set; }

    public DateTime? AdjustmentDate { get; set; }

    public int? EmployeeId { get; set; }

    public string Notes { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<Adjustmentproduct> Adjustmentproducts { get; set; } = new List<Adjustmentproduct>();

    public virtual Employee Employee { get; set; }

    public virtual User User { get; set; }
}