// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Branch
{
    public int BranchId { get; set; }

    public string BranchName { get; set; }

    public string BranchStatus { get; set; }

    public string City { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Country { get; set; }

    public string Location { get; set; }

    public bool? MasterBranch { get; set; }

    public string CommercialRegister { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<Cashandbankaccount> Cashandbankaccounts { get; set; } = new List<Cashandbankaccount>();

    public virtual ICollection<Costcenter> Costcenters { get; set; } = new List<Costcenter>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual ICollection<PosSession> PosSessions { get; set; } = new List<PosSession>();

    public virtual ICollection<Purchaseorder> Purchaseorders { get; set; } = new List<Purchaseorder>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual ICollection<Storehouse> Storehouses { get; set; } = new List<Storehouse>();

    public virtual User User { get; set; }
}