// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Cashandbankaccount
{
    public int AccountId { get; set; }

    public string AccountNumber { get; set; }

    public int? CountryCurrencyId { get; set; }

    public bool? IsAccountingCodeEnabled { get; set; }

    public string Description { get; set; }

    public string AccountName { get; set; }

    public string AccountType { get; set; }

    public string Status { get; set; }

    public int? EmployeeId { get; set; }

    public int? BranchId { get; set; }

    public decimal Balance { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string ShortName { get; set; }

    public string Iban { get; set; }

    public string SwiftCode { get; set; }

    public int? UserId { get; set; }

    public int? ChildAccountId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ChildAccount ChildAccount { get; set; }

    public virtual Countrycurrency CountryCurrency { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Exchange> Exchanges { get; set; } = new List<Exchange>();

    public virtual ICollection<Invoice> InvoiceInvoiceBankAccounts { get; set; } = new List<Invoice>();

    public virtual ICollection<Invoice> InvoiceInvoiceCashAccounts { get; set; } = new List<Invoice>();

    public virtual ICollection<Po> PoBankAccounts { get; set; } = new List<Po>();

    public virtual ICollection<Po> PoCashAccounts { get; set; } = new List<Po>();

    public virtual ICollection<Transfer> TransferFromAccounts { get; set; } = new List<Transfer>();

    public virtual ICollection<Transfer> TransferToAccounts { get; set; } = new List<Transfer>();

    public virtual User User { get; set; }
}