// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class ChildAccount
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int ParentAccountId { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<AccountMapping> AccountMappings { get; set; } = new List<AccountMapping>();

    public virtual ICollection<Cashandbankaccount> Cashandbankaccounts { get; set; } = new List<Cashandbankaccount>();

    public virtual ICollection<Childbalance> Childbalances { get; set; } = new List<Childbalance>();

    public virtual ICollection<ExchangeChildAccount> ExchangeChildAccounts { get; set; } = new List<ExchangeChildAccount>();

    public virtual ICollection<JournalEntry> JournalEntries { get; set; } = new List<JournalEntry>();

    public virtual ParentAccount ParentAccount { get; set; }

    public virtual User User { get; set; }
}