// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Childbalance
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int ChildAccountId { get; set; }

    public decimal Balance { get; set; }

    public virtual ChildAccount ChildAccount { get; set; }

    public virtual User User { get; set; }
}