// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Countrycurrency
{
    public int CountryCurrencyId { get; set; }

    public string CountryName { get; set; }

    public string CurrencyName { get; set; }

    public string CurrencySymbol { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Cashandbankaccount> Cashandbankaccounts { get; set; } = new List<Cashandbankaccount>();
}