// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication4.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public int? UserId { get; set; }

    public string FullName { get; set; }

    public string Position { get; set; }

    public decimal Salary { get; set; }
    [Column(TypeName = "datetime")]

    public DateTime HireDate { get; set; }

    public TimeOnly? AttendanceTime { get; set; }

    public TimeOnly? DepartureTime { get; set; }

    public int? StorehouseId { get; set; }

    public int? BranchId { get; set; }

    public string Role { get; set; }

    public string MobileNumber { get; set; }

    public string SecondaryMobileNumber { get; set; }

    public string Email { get; set; }

    public bool AllowSystemAccess { get; set; }

    public string Password { get; set; }

    public string Country { get; set; }

    public string Region { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string Attachments { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<Adjustment> Adjustments { get; set; } = new List<Adjustment>();

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Cashandbankaccount> Cashandbankaccounts { get; set; } = new List<Cashandbankaccount>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PosSession> PosSessions { get; set; } = new List<PosSession>();

    public virtual ICollection<PosTransaction> PosTransactions { get; set; } = new List<PosTransaction>();

    public virtual ICollection<Purchaseorder> Purchaseorders { get; set; } = new List<Purchaseorder>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual Storehouse Storehouse { get; set; }

    public virtual ICollection<Transfer> Transfers { get; set; } = new List<Transfer>();

    public virtual User User { get; set; }

    public virtual ICollection<Vendor> Vendors { get; set; } = new List<Vendor>();
}