// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class ExchangeChildAccount
{
    public int Id { get; set; }

    public int ExchangeId { get; set; }

    public int ChildAccountId { get; set; }

    public decimal Amount { get; set; }

    public virtual ChildAccount ChildAccount { get; set; }

    public virtual Exchange Exchange { get; set; }
}