// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Inventory
{
    public int InventoryId { get; set; }

    public int? ProductId { get; set; }

    public int IncomingQuantity { get; set; }

    public int OutgoingQuantity { get; set; }

    public int Balance { get; set; }

    public DateTime? LastUpdated { get; set; }

    public int? StorehouseId { get; set; }

    public int? OrderId { get; set; }

    public int? SessionId { get; set; }

    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    public int? EmployeeId { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<Adjustmentproduct> Adjustmentproducts { get; set; } = new List<Adjustmentproduct>();

    public virtual Employee Employee { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual PosSession Session { get; set; }

    public virtual Storehouse Storehouse { get; set; }

    public virtual User User { get; set; }
}