// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Invoicedetail
{
    public int DetailId { get; set; }

    public int? InvoiceId { get; set; }

    public int? ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal LineTotal { get; set; }

    public decimal? VatAmount { get; set; }

    public string InvoiceTyping { get; set; }

    /// <summary>
    /// References the original cart
    /// </summary>
    public string CartId { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Product Product { get; set; }
}