// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication4.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public int? CustomerId { get; set; }

    public int? EmployeeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InvoiceDate { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public string SubscriptionPlan { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Vatrate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string InvoiceType { get; set; }

    public int? Posid { get; set; }

    public int? StorehouseId { get; set; }

    public int? SessionId { get; set; }

    public string CartId { get; set; }

    public int? ItemsCount { get; set; }

    public int? PrintedCount { get; set; }

    public DateTime? PrintedAt { get; set; }

    public int? UserId { get; set; }

    public int? VendorId { get; set; }

    public int? BranchId { get; set; }

    public int? InvoiceCashAccountId { get; set; }

    public int? InvoiceBankAccountId { get; set; }

    public decimal? Vatamount { get; set; }

    public decimal? TotalAmount { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Cashandbankaccount InvoiceBankAccount { get; set; }

    public virtual Cashandbankaccount InvoiceCashAccount { get; set; }

    public virtual ICollection<Invoicedetail> Invoicedetails { get; set; } = new List<Invoicedetail>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Po Pos { get; set; }

    public virtual ICollection<PosTransaction> PosTransactions { get; set; } = new List<PosTransaction>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual PosSession Session { get; set; }

    public virtual Storehouse Storehouse { get; set; }

    public virtual ICollection<Transfer> Transfers { get; set; } = new List<Transfer>();

    public virtual User User { get; set; }

    public virtual Vendor Vendor { get; set; }
}