// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class JournalEntry
{
    public int Id { get; set; }

    public DateOnly EntryDate { get; set; }

    public string Description { get; set; }

    public decimal DebitAmount { get; set; }

    public decimal CreditAmount { get; set; }

    public int UserId { get; set; }


    public DateTime? CreatedAt { get; set; }

    public int? CostCenterId { get; set; }

    public int? InvoiceId { get; set; }


    public string InvoiceType { get; set; }



    public int? ChildAccountId { get; set; }



    public int? ExchangeId { get; set; }

    public virtual ChildAccount ChildAccount { get; set; }

    public virtual Exchange Exchange { get; set; }

    public virtual User User { get; set; }
}