// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication4.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public string OrderType { get; set; }

    public int? CustomerId { get; set; }

    public int? StorehouseId { get; set; }

    public int? ProductId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "datetime")]

    public DateTime? OrderDate { get; set; }

    public string Notes { get; set; }

    public int? EmployeeId { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal Total { get; set; }

    public int? UserId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual Product Product { get; set; }

    public virtual Storehouse Storehouse { get; set; }

    public virtual User User { get; set; }
}