// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Payment
{
    public int Payid { get; set; }

    public int? CustomerId { get; set; }

    public int? VendorId { get; set; }

    public int UserId { get; set; }

    public DateOnly Paydate { get; set; }

    public decimal TotalAmount { get; set; }

    public string PaymentStatus { get; set; }

    public string PaymentMethod { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? InvoiceId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual ICollection<Paymentdetail> Paymentdetails { get; set; } = new List<Paymentdetail>();

    public virtual User User { get; set; }

    public virtual Vendor Vendor { get; set; }
}