// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Po
{
    public int Posid { get; set; }

    public int BranchId { get; set; }

    public string Status { get; set; }

    public string Posname { get; set; }

    public int? CashAccountId { get; set; }

    public int? BankAccountId { get; set; }

    public int? StorehouseId { get; set; }

    public string ReferenceNumber { get; set; }

    public string Notes { get; set; }

    public string Attachments { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? SessionId { get; set; }

    public string CartId { get; set; }

    public int? UserId { get; set; }

    public virtual Cashandbankaccount BankAccount { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Cashandbankaccount CashAccount { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<PosSession> PosSessions { get; set; } = new List<PosSession>();

    public virtual PosSession Session { get; set; }

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual Storehouse Storehouse { get; set; }

    public virtual User User { get; set; }
}