// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class PosCart
{
    public string CartId { get; set; }

    public int SessionId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal? DiscountPercent { get; set; }

    public DateTime AddedAt { get; set; }

    public string Status { get; set; }

    public virtual Product Product { get; set; }

    public virtual PosSession Session { get; set; }
}