// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class PosPaymentMethod
{
    public int MethodId { get; set; }

    public string MethodName { get; set; }

    public string MethodType { get; set; }

    public string Icon { get; set; }

    public bool? IsActive { get; set; }

    public int? DisplayOrder { get; set; }
}