// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class PosSession
{
    public int SessionId { get; set; }

    public int Posid { get; set; }

    public int? EmployeeId { get; set; }

    public int StorehouseId { get; set; }

    public int BranchId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public decimal StartingCash { get; set; }

    public decimal? EndingCash { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public int? UserId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual ICollection<PosCart> PosCarts { get; set; } = new List<PosCart>();

    public virtual Po PosNavigation { get; set; }

    public virtual Storehouse Storehouse { get; set; }

    public virtual User User { get; set; }
}