// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class PosTransaction
{
    public int TransactionId { get; set; }

    public int? EmployeeId { get; set; }

    public int? InvoiceId { get; set; }

    public string PaymentMethod { get; set; }

    public decimal AmountPaid { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Invoice Invoice { get; set; }
}