// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public decimal Price { get; set; }

    public DateTime? CreatedAt { get; set; }

    public decimal? Vatrate { get; set; }

    public byte[] Image { get; set; }

    public string Qrcode { get; set; }

    public decimal PurchasePrice { get; set; }

    public int RepurchasePoint { get; set; }

    public int Balance { get; set; }

    public int? StorehouseId { get; set; }

    public int? CategoryId { get; set; }

    public bool? IsActive { get; set; }

    public DateOnly? LastRestocked { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<Adjustmentproduct> Adjustmentproducts { get; set; } = new List<Adjustmentproduct>();

    public virtual ProductCategory Category { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<Invoicedetail> Invoicedetails { get; set; } = new List<Invoicedetail>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PosCart> PosCarts { get; set; } = new List<PosCart>();

    public virtual ICollection<Purchaseorderdetail> Purchaseorderdetails { get; set; } = new List<Purchaseorderdetail>();

    public virtual ICollection<Quotationdetail> Quotationdetails { get; set; } = new List<Quotationdetail>();

    public virtual Storehouse Storehouse { get; set; }

    public virtual User User { get; set; }
}