// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Purchaseorder
{
    public int PurchaseOrderId { get; set; }

    public int? VendorId { get; set; }

    public int? EmployeeId { get; set; }

    public DateOnly PurchaseOrderDate { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public string Status { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Vatrate { get; set; }

    public decimal? Vatamount { get; set; }

    public decimal? TotalAmount { get; set; }

    public int? StorehouseId { get; set; }

    public int ItemsCount { get; set; }

    public int? BranchId { get; set; }

    public int? UserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Purchaseorderdetail> Purchaseorderdetails { get; set; } = new List<Purchaseorderdetail>();

    public virtual Storehouse Storehouse { get; set; }

    public virtual User User { get; set; }

    public virtual Vendor Vendor { get; set; }
}