// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication4.Models;

public partial class Quotation
{
    public int QuotationId { get; set; }

    public int? CustomerId { get; set; }

    public int? EmployeeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime QuotationDate { get; set; }
    [Column(TypeName = "datetime")]
    public DateTime ExpiryDate { get; set; }


    public string Status { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Vatrate { get; set; }

    public decimal? Vatamount { get; set; }

    public decimal? TotalAmount { get; set; }

    public int? StorehouseId { get; set; }

    public int? InvoiceId { get; set; }

    public DateTime CreatedAt { get; set; }

    public int ItemsCount { get; set; }

    public int? BranchId { get; set; }

    public int? UserId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual ICollection<Quotationdetail> Quotationdetails { get; set; } = new List<Quotationdetail>();

    public virtual Storehouse Storehouse { get; set; }

    public virtual User User { get; set; }
}