// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Shift
{
    public int ShiftId { get; set; }

    public DateTime StartDateTime { get; set; }

    public int ShiftHours { get; set; }

    public int EmployeeId { get; set; }

    public int Posid { get; set; }

    public bool? RepeatWeekly { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string RepeatDays { get; set; }

    public string Notes { get; set; }

    public int? UserId { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Po Pos { get; set; }

    public virtual User User { get; set; }
}