// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Sitestat
{
    public int StatId { get; set; }

    public string PageName { get; set; }

    public int Views { get; set; }

    public int Visitors { get; set; }

    public DateTime? LastUpdated { get; set; }
}