// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Storehouse
{
    public int StorehouseId { get; set; }

    public string StorehouseName { get; set; }

    public string Location { get; set; }

    public string SubLocation { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string DetailedLocation { get; set; }

    public bool? Status { get; set; }

    public int? CurrentQuantity { get; set; }

    public int? BranchId { get; set; }

    public int? UserId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual ICollection<PosSession> PosSessions { get; set; } = new List<PosSession>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Purchaseorder> Purchaseorders { get; set; } = new List<Purchaseorder>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual User User { get; set; }
}