// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class TriggerLog
{
    public long Id { get; set; }

    public string TriggerName { get; set; }

    public string Action { get; set; }

    public int? UserId { get; set; }

    public int? ChildAccountId { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? CreatedAt { get; set; }
}