// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Vendor
{
    public int VendorId { get; set; }

    public string VendorName { get; set; }

    public string PhoneNumber1 { get; set; }

    public string PhoneNumber2 { get; set; }

    public string Email { get; set; }

    public string TaxNumber { get; set; }

    public bool? TaxableCheck { get; set; }

    public string Classification { get; set; }

    public string CommercialRegister { get; set; }

    public string Location { get; set; }

    public string Currency { get; set; }

    public decimal? CreditLimit { get; set; }

    public int UserId { get; set; }

    public int? EmployeeId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Exchange> Exchanges { get; set; } = new List<Exchange>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Purchaseorder> Purchaseorders { get; set; } = new List<Purchaseorder>();

    public virtual User User { get; set; }
}